char *template_c_types[] = {
"MODULE ModName_C_Types",
"",
"  USE , INTRINSIC :: ISO_C_Binding",
"  IMPLICIT NONE",
"",
"  PRIVATE",
"",
"  !==========   ModName C++ Object Pointers   ======     <-----------------------+",
"  ! Fortran types that will be binded with C++.                   !          |",
"  ! These types are pointers to C++ objects.                      !          |",
"  !                                                               !          |",
"  ! Initialization Input States                                   !          |",
"  TYPE , BIND(C) :: ModName_InitInput_C                               !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_InitInput_C                                        !          |",
"                                                                  !          |",
"  TYPE , BIND(C) :: ModName_InitOutput_C                               !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_InitOutput_C                                        !          |",
"                                                                  !          |",
"  ! Input States                                                  !          |",
"  TYPE , BIND(C) :: ModName_Input_C                                   !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_Input_C                                            !          |",
"                                                                  !          |",
"  ! Parameter States                                              !          |",
"  TYPE , BIND(C) :: ModName_Param_C                               !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_Param_C                                        !          |",
"                                                                  !          |",
"  ! Continuous States                                             !          |",
"  TYPE , BIND(C) :: ModName_ContState_C                              !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_ContState_C                                       !          |",
"                                                                  !          |",
"  ! Discrete States                                               !          |",
"  TYPE , BIND(C) :: ModName_DiscState_C                                !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_DiscState_C                                         !          |",
"                                                                  !          |",
"  ! Constraint States                                             !          |",
"  TYPE , BIND(C) :: ModName_ConstrState_C                              !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_ConstrState_C                                       !          |",
"                                                                  !          |",
"  ! Other States                                                  !          |",
"  TYPE , BIND(C) :: ModName_OtherState_C                                   !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_OtherState_C                                            !          |",
"                                                                  !          |",
"  ! Output States                                                 !          |",
"  TYPE , BIND(C) :: ModName_Output_C                                  !          |",
"     PRIVATE                                                      !          |",
"     TYPE(C_ptr) :: object = C_NULL_ptr                           !          |",
"  END TYPE ModName_Output_C                                           !   -------+",
"  !===========================================================================",
"",
"",
"  !==========   ModName Object Constructor/Destructor   ======     <------------------------------+",
"  !                                                                                !          |       ",
"  INTERFACE ! BEGIN: Interface to external C functions                             !          |     ",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize Initialization Input object                      !          |     !          |",
"     FUNCTION C_Create_ModName_InitInput( ) RESULT( this ) &          !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_InitInput_Create\" )                 !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_InitInput                          !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_InitInput( this ) &                  !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_InitInput_Delete\" )                 !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_InitInput                        !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize Initialization Output object                      !          |     !          |",
"     FUNCTION C_Create_ModName_InitOutput( ) RESULT( this ) &          !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_InitOutput_Create\" )                 !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_InitOutput                          !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_InitOutput( this ) &                  !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_InitOutput_Delete\" )                 !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_InitOutput                        !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize Input object                                     !          |     !          |",
"     FUNCTION C_Create_ModName_Input( ) RESULT( this ) &              !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_Input_Create\" )                     !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_Input                              !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_Input( this ) &                      !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_Input_Delete\" )                     !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_Input                            !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize input object                                     !          |     !          |",
"     FUNCTION C_Create_ModName_Parameter( ) RESULT( this ) &          !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_Param_Create\" )                 !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_Parameter                          !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_Parameter( this ) &                  !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_Param_Delete\" )                 !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_Parameter                        !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize input object                                     !          |     !          |",
"     FUNCTION C_Create_ModName_Continuous( ) RESULT( this ) &         !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_ContState_Create\" )                !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_Continuous                         !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_Continuous( this ) &                 !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_ContState_Delete\" )                !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_Continuous                       !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize input object                                     !          |     !          |",
"     FUNCTION C_Create_ModName_Discrete( ) RESULT( this ) &           !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_DiscState_Create\" )                  !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_Discrete                           !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_Discrete( this ) &                   !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_DiscState_Delete\" )                  !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_Discrete                         !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize input object                                     !          |     !          |",
"     FUNCTION C_Create_ModName_Constraint( ) RESULT( this ) &         !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_ConstrState_Create\" )                !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_Constraint                         !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_Constraint( this ) &                 !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_ConstrState_Delete\" )                !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_Constraint                       !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize input object                                     !          |     !          |",
"     FUNCTION C_Create_ModName_Other( ) RESULT( this ) &              !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_OtherState_Create\" )                     !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_Other                              !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_Other( this ) &                      !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_OtherState_Delete\" )                     !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_Other                            !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"                                                                                   !          |",
"     !==========   ModName C++ Object Constructor/Destructor   ======     <------+     !          |",
"     !                                                            !          |     !          |",
"     ! Initalize input object                                     !          |     !          |",
"     FUNCTION C_Create_ModName_Output( ) RESULT( this ) &             !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_Output_Create\" )                    !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr) :: this                                        !          |     !          |",
"     END FUNCTION C_Create_ModName_Output                             !          |     !          |",
"                                                                  !          |     !          |",
"     ! Delete input object                                        !          |     !          |",
"     SUBROUTINE C_Delete_ModName_Output( this ) &                     !          |     !          |",
"          !NAME = the C function called inside ' extern \"C\" '     !          |     !          |",
"          BIND( C , NAME=\"ModName_Output_Delete\" )                    !          |     !          |",
"       IMPORT                                                     !          |     !          |",
"       TYPE(C_ptr), VALUE :: this                                 !          |     !          |",
"     END SUBROUTINE C_Delete_ModName_Output                           !   -------+     !          |",
"     !========================================================================     !          |",
"                                                                                   !          |",
"  END INTERFACE ! END: Interface to external C functions                           !   -------+",
"  !============================================================================================",
"",
"",
"  !==========   ModName C++ Object Interface   ======     <-------------------+",
"  !                                                            !          |",
"  ! Input initalize interface                                  !          |                                                            ",
"  INTERFACE ModName_InitInput_Initialize                            !          |",
"     MODULE PROCEDURE ModName_InitInput_Create                     !          |",
"  END INTERFACE ModName_InitInput_Initialize                        !          |",
"                                                               !          |",
"  ! Input destructor interface                                 !          |",
"  INTERFACE ModName_InitInput_Destroy                              !          |",
"     MODULE PROCEDURE ModName_InitInput_Delete                     !          |",
"  END INTERFACE ModName_InitInput_Destroy                          !          |",
"                                                               !          |",
"  ! Output initalize interface                                  !          |   ",
"  INTERFACE ModName_InitOutput_Initialize                            !          |",
"     MODULE PROCEDURE ModName_InitOutput_Create                     !          |",
"  END INTERFACE ModName_InitOutput_Initialize                        !          |",
"                                                               !          |",
"  ! Output destructor interface                                 !          |",
"  INTERFACE ModName_InitOutput_Destroy                              !          |",
"     MODULE PROCEDURE ModName_InitOutput_Delete                     !          |",
"  END INTERFACE ModName_InitOutput_Destroy                          !          |",
"                                                               !          |",
"  ! Input Constructor interface                                !          |",
"  INTERFACE ModName_Input_Initialize                                !          |",
"     MODULE PROCEDURE ModName_Input_Create                         !          |",
"  END INTERFACE ModName_Input_Initialize                            !          |",
"                                                               !          |",
"  ! Input Destructor interface                                 !          |",
"  INTERFACE ModName_Input_Destroy                                  !          |",
"     MODULE PROCEDURE ModName_Input_Delete                         !          |",
"  END INTERFACE ModName_Input_Destroy                              !          |",
"                                                               !          |",
"                                                               !          |",
"  ! Input initalize interface                                  !          |",
"  INTERFACE ModName_Parameter_Initialize                            !          |",
"     MODULE PROCEDURE ModName_Param_Create                     !          |",
"  END INTERFACE ModName_Parameter_Initialize                        !          |",
"  ! Input Destructor interface                                 !          |",
"  INTERFACE ModName_Parameter_Destroy                              !          |",
"     MODULE PROCEDURE ModName_Parameter_Delete                     !          |",
"  END INTERFACE ModName_Parameter_Destroy                          !          |",
"                                                               !          |",
"                                                               !          |",
"  ! Input initalize interface                                  !          |",
"  INTERFACE ModName_Continuous_Initialize                           !          |",
"     MODULE PROCEDURE ModName_ContState_Create                    !          |",
"  END INTERFACE ModName_Continuous_Initialize                       !          |",
"  ! Input Destructor interface                                 !          |",
"  INTERFACE ModName_Continuous_Destroy                             !          |",
"     MODULE PROCEDURE ModName_Continuous_Delete                    !          |",
"  END INTERFACE ModName_Continuous_Destroy                         !          |",
"                                                               !          |",
"                                                               !          |",
"  ! Input initalize interface                                  !          |",
"  INTERFACE ModName_Discrete_Initialize                             !          |",
"     MODULE PROCEDURE ModName_DiscState_Create                      !          |",
"  END INTERFACE ModName_Discrete_Initialize                         !          |",
"  ! Input Destructor interface                                 !          |",
"  INTERFACE ModName_Discrete_Destroy                               !          |",
"     MODULE PROCEDURE ModName_Discrete_Delete                      !          |",
"  END INTERFACE ModName_Discrete_Destroy                           !          |",
"                                                               !          |",
"                                                               !          |",
"  ! Input initalize interface                                  !          |",
"  INTERFACE ModName_Constraint_Initialize                           !          |",
"     MODULE PROCEDURE ModName_ConstrState_Create                    !          |",
"  END INTERFACE ModName_Constraint_Initialize                       !          |",
"  ! Input Destructor interface                                 !          |",
"  INTERFACE ModName_Constraint_Destroy                             !          |",
"     MODULE PROCEDURE ModName_Constraint_Delete                    !          |",
"  END INTERFACE ModName_Constraint_Destroy                         !          |",
"                                                               !          |",
"                                                               !          |",
"  ! Input initalize interface                                  !          |",
"  INTERFACE ModName_Other_Initialize                                !          |",
"     MODULE PROCEDURE ModName_OtherState_Create                         !          |",
"  END INTERFACE ModName_Other_Initialize                            !          |",
"  ! Input Destructor interface                                 !          |",
"  INTERFACE ModName_Other_Destroy                                  !          |",
"     MODULE PROCEDURE ModName_Other_Delete                         !          |",
"  END INTERFACE ModName_Other_Destroy                              !          |",
"                                                               !          |",
"                                                               !          |",
"  ! Input initalize interface                                  !          |",
"  INTERFACE ModName_Output_Initialize                               !          |",
"     MODULE PROCEDURE ModName_Output_Create                        !          |",
"  END INTERFACE ModName_Output_Initialize                           !          |",
"  ! Input Destructor interface                                 !          |",
"  INTERFACE ModName_Output_Destroy                                 !          |",
"     MODULE PROCEDURE ModName_Output_Delete                        !          |",
"  END INTERFACE ModName_Output_Destroy                             !   -------+",
"  !========================================================================",
"",
"",
"  PUBLIC :: ModName_InitInput_C     , &",
"       ModName_InitOutput_C        , &",
"       ModName_Input_C              , &",
"       ModName_Param_C          , &",
"       ModName_ContState_C         , &",
"       ModName_DiscState_C           , &",
"       ModName_ConstrState_C         , &",
"       ModName_OtherState_C              , &",
"       ModName_Output_C             , &",
"       ModName_InitInput_Initialize  , & ",
"       ModName_InitOutput_Initialize  , & ",
"       ModName_Input_Initialize      , & ",
"       ModName_Parameter_Initialize  , & ",
"       ModName_Continuous_Initialize , & ",
"       ModName_Discrete_Initialize   , &",
"       ModName_Constraint_Initialize , &",
"       ModName_Other_Initialize      , &",
"       ModName_Output_Initialize     , &",
"       ModName_InitInput_Destroy    , &",
"       ModName_InitOutput_Destroy    , &",
"       ModName_Input_Destroy        , &",
"       ModName_Parameter_Destroy    , &",
"       ModName_Continuous_Destroy   , &",
"       ModName_Discrete_Destroy     , &",
"       ModName_Constraint_Destroy   , &",
"       ModName_Other_Destroy        , &",
"       ModName_Output_Destroy       ",
"",
"CONTAINS",
"",
"  !==========   ModName C++ Object Interface   ======     <-------------------+",
"  !                                                            !          |",
"",
"  ! Initialization Input type construction",
"  SUBROUTINE ModName_InitInput_Create( this )",
"    TYPE( ModName_InitInput_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_InitInput( )",
"  END SUBROUTINE ModName_InitInput_Create",
"  ! Initlialization Input type destruction",
"  SUBROUTINE ModName_InitInput_Delete(this)",
"    TYPE( ModName_InitInput_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_InitInput( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_InitInput_Delete",
"",
"",
"  ! Initialization Output type construction",
"  SUBROUTINE ModName_InitOutput_Create( this )",
"    TYPE( ModName_InitOutput_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_InitOutput( )",
"  END SUBROUTINE ModName_InitOutput_Create",
"  ! Initlialization Output type destruction",
"  SUBROUTINE ModName_InitOutput_Delete(this)",
"    TYPE( ModName_InitOutput_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_InitOutput( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_InitOutput_Delete",
"",
"",
"  ! Input type initialization",
"  SUBROUTINE ModName_Input_Create( this )",
"    TYPE( ModName_Input_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_Input( )",
"  END SUBROUTINE ModName_Input_Create",
"  ! Input type destruction",
"  SUBROUTINE ModName_Input_Delete(this)",
"    TYPE( ModName_Input_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_Input( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_Input_Delete",
"",
"",
"  ! Parameter type initialization",
"  SUBROUTINE ModName_Param_Create( this )",
"    TYPE( ModName_Param_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_Parameter( )",
"  END SUBROUTINE ModName_Param_Create",
"  ! Parameter type destruction",
"  SUBROUTINE ModName_Parameter_Delete(this)",
"    TYPE( ModName_Param_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_Parameter( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_Parameter_Delete",
"",
"",
"  ! Continuous type initialization",
"  SUBROUTINE ModName_ContState_Create( this )",
"    TYPE( ModName_ContState_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_Continuous( )",
"  END SUBROUTINE ModName_ContState_Create",
"  ! Continuous type destruction",
"  SUBROUTINE ModName_Continuous_Delete(this)",
"    TYPE( ModName_ContState_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_Continuous( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_Continuous_Delete",
"",
"",
"  ! Discrete type initialization",
"  SUBROUTINE ModName_DiscState_Create( this )",
"    TYPE( ModName_DiscState_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_Discrete( )",
"  END SUBROUTINE ModName_DiscState_Create",
"  ! Discrete type destruction",
"  SUBROUTINE ModName_Discrete_Delete(this)",
"    TYPE( ModName_DiscState_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_Discrete( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_Discrete_Delete",
"",
"",
"  ! Constraint type initialization",
"  SUBROUTINE ModName_ConstrState_Create( this )",
"    TYPE( ModName_ConstrState_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_Constraint( )",
"  END SUBROUTINE ModName_ConstrState_Create",
"  ! Constraint type destruction",
"  SUBROUTINE ModName_Constraint_Delete(this)",
"    TYPE( ModName_ConstrState_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_Constraint( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_Constraint_Delete",
"",
"",
"  ! Other type initialization",
"  SUBROUTINE ModName_OtherState_Create( this )",
"    TYPE( ModName_OtherState_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_Other( )",
"  END SUBROUTINE ModName_OtherState_Create",
"  ! Other type destruction",
"  SUBROUTINE ModName_Other_Delete(this)",
"    TYPE( ModName_OtherState_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_Other( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_Other_Delete",
"",
"",
"  ! Output type initialization",
"  SUBROUTINE ModName_Output_Create( this )",
"    TYPE( ModName_Output_C ), INTENT( OUT ) :: this",
"    this%object = C_Create_ModName_Output( )",
"  END SUBROUTINE ModName_Output_Create",
"  ! Output type destruction",
"  SUBROUTINE ModName_Output_Delete(this)",
"    TYPE( ModName_Output_C ), INTENT(INOUT) :: this",
"    CALL C_Delete_ModName_Output( this%object )",
"    this%object = C_NULL_ptr",
"  END SUBROUTINE ModName_Output_Delete                             !   -------+",
"  !========================================================================",
"",
"END MODULE ModName_C_Types",
0L } ;
