name: 'Compile OpenFAST'
description: 'Compile part or all of OpenFAST'
author: 'Rafael Mudafort https://github.com/rafmudaf'

inputs:
  build-target:
    description: 'Which targets to compile'
    default: 'install'

runs:
  using: 'composite'
  steps:
    - run: make -j4 ${{ inputs.build-target }}
      working-directory: "/openfast/build"
      shell: bash
