sed s/"ED_P_2_NStC_P_N"/"ED_P_2_NStC_P_N"/g -i *
sed s/"NStC_P_2_ED_P_N"/"NStC_P_2_ED_P_N"/g -i *
sed s/"ED_L_2_TStC_P_T"/"ED_L_2_TStC_P_T"/g -i *
sed s/"TStC_P_2_ED_P_T"/"TStC_P_2_ED_P_T"/g -i *
sed s/"ED_L_2_BStC_P_B"/"ED_L_2_BStC_P_B"/g -i *
sed s/"BStC_P_2_ED_P_B"/"BStC_P_2_ED_P_B"/g -i *
sed s/"BD_L_2_BStC_P_B"/"BD_L_2_BStC_P_B"/g -i *
sed s/"BStC_P_2_BD_P_B"/"BStC_P_2_BD_P_B"/g -i *
sed s/"SStC_P_P_2_ED_P"/"SStC_P_P_2_ED_P"/g -i *
sed s/"ED_P_2_SStC_P_P"/"ED_P_2_SStC_P_P"/g -i *
sed s/"SStC_P_P_2_SD_P"/"SStC_P_P_2_SD_P"/g -i *
sed s/"SD_P_2_SStC_P_P"/"SD_P_2_SStC_P_P"/g -i *
