name: 'AeroDyn module tests'
description: 'Run tests specific to the AeroDyn module'
author: 'Rafael Mudafort https://github.com/rafmudaf'
runs:
  using: "composite"
  steps: 
    - run: ctest -VV -R fvw_utest
      working-directory: "/openfast/build"
      shell: bash
