.Id $Id: asa.1,v 1.2 1994/04/12 22:43:11 tom Exp $
.TH ASA 1 "April 1994" POSIX.2 "Linux Programmer's Manual"
.SH NAME
asa \- convert ASA (Fortran) carriage control charachters
.SH SYNOPSIS
.B asa
.RI [ file ...]
.SH DESCRIPTION
.B asa
reads text with ASA cariage control characters from the files specified
as its command arguments, or standard input if none are specified, and
converts them into line printer control sequences.
.PP
These control characters are traditionally used in Fortran programs.
.PP
The first character of every line is removed from input, and the following
actions are performed:
.PP
If the caracter removed is:
.TP 8
.B <space>
the rest of the line is output without change.
.TP 8
.B 0
a
.B <newline>
is output, then the rest of the input line.
.TP 8
.BR 1
a
.B <form feed>
is output, then the rest of the input line.
.TP 8
.B +
An attempt is made to overstrike the previous line with the one following
the character; this can be used for emphasis.
.TP 8
.B <any other character>
The same actions as for a
.B <space>
are performed; this is an extension of the POSIX.2 standard.
.PP
The overstriking generated may be removed by piping the output through
.BR "col -b".
.PP
Tabs in the input file are expanded to a width of eight.
.SH BUGS
It is not be possible to use the
.B asa
filter for interactive use in Fortran programs, because of the semantics of
the
.B +
character, and because I/O is buffered.
.SH "CONFORMS TO"
POSIX.2
.SH "SEE ALSO"
f2c(1), f77(1), col(1)
