"""Blade CRUD endpoints with ElastoDyn and AeroDyn file previews."""

from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import PlainTextResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies import get_current_user
from app.models.components import Blade
from app.models.project import Project
from app.models.user import User
from app.schemas.components import BladeCreate, BladeResponse, BladeUpdate

router = APIRouter(prefix="/projects/{project_id}/blades", tags=["blades"])


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
async def _verify_project(project_id: UUID, org_id: UUID, db: AsyncSession) -> Project:
    result = await db.execute(
        select(Project).where(Project.id == project_id, Project.org_id == org_id)
    )
    project = result.scalar_one_or_none()
    if project is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Project not found")
    return project


async def _get_blade_or_404(blade_id: UUID, project_id: UUID, db: AsyncSession) -> Blade:
    result = await db.execute(
        select(Blade).where(Blade.id == blade_id, Blade.project_id == project_id)
    )
    blade = result.scalar_one_or_none()
    if blade is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Blade not found")
    return blade


def _generate_elastodyn_blade_file(blade: Blade, project: Project) -> str:
    """Generate an ElastoDyn blade input file."""
    lines: list[str] = []
    lines.append("------- ELASTODYN BLADE FILE -----------------------------------------------")
    lines.append(f"Generated by WindForge for blade: {blade.name} v{blade.version}")
    lines.append(f"Project: {project.name}")
    lines.append(
        "---------------------- BLADE PARAMETERS ------------------------------------"
    )
    lines.append(f"{blade.blade_length:<14}   BldFlexL   - Blade flexible length (m)")

    # Mode shapes
    lines.append(
        "---------------------- BLADE FLAP MODE SHAPES ------------------------------"
    )
    flap1 = blade.flap_mode_1_coeffs or [0.0, 0.0, 0.0, 0.0, 0.0]
    flap2 = blade.flap_mode_2_coeffs or [0.0, 0.0, 0.0, 0.0, 0.0]
    for i, c in enumerate(flap1):
        lines.append(f"{c:<14.6E}   BldFl1Sh({i+2}) - Flap mode 1, x^{i+2} coefficient")
    for i, c in enumerate(flap2):
        lines.append(f"{c:<14.6E}   BldFl2Sh({i+2}) - Flap mode 2, x^{i+2} coefficient")

    lines.append(
        "---------------------- BLADE EDGE MODE SHAPES ------------------------------"
    )
    edge1 = blade.edge_mode_1_coeffs or [0.0, 0.0, 0.0, 0.0, 0.0]
    for i, c in enumerate(edge1):
        lines.append(f"{c:<14.6E}   BldEdgSh({i+2}) - Edge mode 1, x^{i+2} coefficient")

    # Damping
    lines.append(
        "---------------------- BLADE DAMPING ----------------------------------------"
    )
    lines.append(
        f"{blade.blade_flap_damping:<14}   BldFlDmp(1) - Blade flap structural damping (%)"
    )
    lines.append(
        f"{blade.blade_edge_damping:<14}   BldEdDmp(1) - Blade edge structural damping (%)"
    )

    # Structural stations
    struct_stations = blade.structural_stations or []
    n_st = len(struct_stations)
    lines.append(
        "---------------------- DISTRIBUTED BLADE PROPERTIES -------------------------"
    )
    lines.append(f"{n_st:<14}   NBlInpSt   - Number of blade input stations")
    lines.append(
        "BlFract   PitchAxis  StrcTwst   BMassDen   FlpStff    EdgStff"
    )
    lines.append(
        "(-)       (-)        (deg)      (kg/m)     (Nm^2)     (Nm^2)"
    )
    for st in struct_stations:
        frac = st.get("frac", 0.0)
        pa = st.get("pitch_axis", 0.0)
        tw = st.get("struct_twist", 0.0)
        md = st.get("mass_den", 0.0)
        fs = st.get("flap_stiff", 0.0)
        es = st.get("edge_stiff", 0.0)
        lines.append(
            f"{frac:<10.4f}{pa:<11.4f}{tw:<11.4f}{md:<11.2f}{fs:<14.4E}{es:<14.4E}"
        )

    lines.append(
        "---------------------- END OF FILE -----------------------------------------"
    )
    return "\n".join(lines)


def _generate_aerodyn_blade_file(blade: Blade, project: Project) -> str:
    """Generate an AeroDyn blade input file."""
    lines: list[str] = []
    lines.append("------- AERODYN BLADE FILE -------------------------------------------------")
    lines.append(f"Generated by WindForge for blade: {blade.name} v{blade.version}")
    lines.append(f"Project: {project.name}")
    lines.append(
        "---------------------- BLADE AERODYNAMIC PROPERTIES -------------------------"
    )

    aero_stations = blade.aero_stations or []
    n_aero = len(aero_stations)
    lines.append(f"{n_aero:<14}   NumBlNds   - Number of blade nodes")
    lines.append(
        "BlSpn      BlCrvAC    BlSwpAC    BlCrvAng   BlTwist    BlChord    BlAFID"
    )
    lines.append(
        "(m)        (m)        (m)        (deg)      (deg)      (m)        (-)"
    )
    for st in aero_stations:
        frac = st.get("frac", 0.0)
        span = frac * blade.blade_length
        twist = st.get("aero_twist", 0.0)
        chord = st.get("chord", 0.0)
        af_id = st.get("airfoil_id", "N/A")
        ac = st.get("aero_center", 0.25)
        lines.append(
            f"{span:<11.4f}{0.0:<11.4f}{0.0:<11.4f}{0.0:<11.4f}"
            f"{twist:<11.4f}{chord:<11.4f}{af_id}"
        )

    lines.append(
        "---------------------- END OF FILE -----------------------------------------"
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# endpoints
# ---------------------------------------------------------------------------

@router.get("/", response_model=list[BladeResponse])
async def list_blades(
    project_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await _verify_project(project_id, current_user.org_id, db)
    result = await db.execute(
        select(Blade)
        .where(Blade.project_id == project_id)
        .order_by(Blade.created_at.desc())
    )
    return [BladeResponse.model_validate(b) for b in result.scalars().all()]


@router.post("/", response_model=BladeResponse, status_code=status.HTTP_201_CREATED)
async def create_blade(
    project_id: UUID,
    body: BladeCreate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await _verify_project(project_id, current_user.org_id, db)

    data = body.model_dump(exclude_unset=True)
    if "structural_stations" in data and data["structural_stations"] is not None:
        data["structural_stations"] = [
            s.model_dump() if hasattr(s, "model_dump") else s
            for s in data["structural_stations"]
        ]
    if "aero_stations" in data and data["aero_stations"] is not None:
        data["aero_stations"] = [
            s.model_dump() if hasattr(s, "model_dump") else s for s in data["aero_stations"]
        ]

    blade = Blade(project_id=project_id, **data)
    db.add(blade)
    await db.flush()
    await db.refresh(blade)
    return BladeResponse.model_validate(blade)


@router.get("/{blade_id}", response_model=BladeResponse)
async def get_blade(
    project_id: UUID,
    blade_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await _verify_project(project_id, current_user.org_id, db)
    blade = await _get_blade_or_404(blade_id, project_id, db)
    return BladeResponse.model_validate(blade)


@router.put("/{blade_id}", response_model=BladeResponse)
async def update_blade(
    project_id: UUID,
    blade_id: UUID,
    body: BladeUpdate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await _verify_project(project_id, current_user.org_id, db)
    blade = await _get_blade_or_404(blade_id, project_id, db)

    update_data = body.model_dump(exclude_unset=True)
    if "structural_stations" in update_data and update_data["structural_stations"] is not None:
        update_data["structural_stations"] = [
            s.model_dump() if hasattr(s, "model_dump") else s
            for s in update_data["structural_stations"]
        ]
    if "aero_stations" in update_data and update_data["aero_stations"] is not None:
        update_data["aero_stations"] = [
            s.model_dump() if hasattr(s, "model_dump") else s
            for s in update_data["aero_stations"]
        ]

    for field, value in update_data.items():
        setattr(blade, field, value)

    blade.version += 1
    await db.flush()
    await db.refresh(blade)
    return BladeResponse.model_validate(blade)


@router.delete("/{blade_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_blade(
    project_id: UUID,
    blade_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    await _verify_project(project_id, current_user.org_id, db)
    blade = await _get_blade_or_404(blade_id, project_id, db)
    await db.delete(blade)
    await db.flush()


@router.get("/{blade_id}/preview-ed", response_class=PlainTextResponse)
async def preview_blade_elastodyn(
    project_id: UUID,
    blade_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Preview the ElastoDyn blade input file."""
    project = await _verify_project(project_id, current_user.org_id, db)
    blade = await _get_blade_or_404(blade_id, project_id, db)
    return _generate_elastodyn_blade_file(blade, project)


@router.get("/{blade_id}/preview-ad", response_class=PlainTextResponse)
async def preview_blade_aerodyn(
    project_id: UUID,
    blade_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Preview the AeroDyn blade input file."""
    project = await _verify_project(project_id, current_user.org_id, db)
    blade = await _get_blade_or_404(blade_id, project_id, db)
    return _generate_aerodyn_blade_file(blade, project)
