name: 'HydroDyn module tests'
description: 'Run tests specific to the HydroDyn module'
author: 'Rafael Mudafort https://github.com/rafmudaf'
runs:
  using: "composite"
  steps:  
    - run: ctest -VV -j7 -R hd_
      working-directory: ${{runner.workspace}}/openfast/build
      shell: bash
