"""AeroDisk standalone driver — reads/writes AeroDisk driver input files (.dvr).

Uses right-aligned values and ``@filename.csv`` syntax for timeseries data.
Handles geometry, environment, and case analysis parameters.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict

from ..io.aerodisk import AeroDiskIO
from ..parsing import bool_read, float_read, int_read, quoted_read


class AeroDiskStandaloneDriver:
    """Reads and writes AeroDisk standalone driver input files (.dvr)."""

    def __init__(self) -> None:
        self._aerodisk = AeroDiskIO()

    # ------------------------------------------------------------------
    # READ
    # ------------------------------------------------------------------
    def read(self, dvr_path: Path) -> dict:
        """Read an AeroDisk driver file and the referenced AeroDisk input.

        Returns a dict with keys:
          ``'AeroDiskDriver'`` — driver-level parameters
          ``'AeroDisk'`` — from AeroDiskIO
        """
        dvr_path = Path(dvr_path)
        base_dir = dvr_path.parent
        dvr: Dict[str, Any] = {}

        with open(dvr_path) as f:
            # --- Header ---
            f.readline()  # title line
            dvr['description'] = f.readline().rstrip()

            # --- Echo ---
            f.readline()  # separator
            dvr['Echo'] = bool_read(f.readline().split()[0])

            # --- Input files ---
            f.readline()  # separator
            dvr['ADskIptFile'] = quoted_read(f.readline().split()[0])
            dvr['OutRootName'] = quoted_read(f.readline().split()[0])

            # --- Geometry and Environment ---
            f.readline()  # section header
            dvr['AirDens'] = float_read(f.readline().split()[0])
            dvr['RotorRad'] = float_read(f.readline().split()[0])
            dvr['RotorHeight'] = float_read(f.readline().split()[0])
            dvr['ShftTilt'] = float_read(f.readline().split()[0])

            # --- Case Analysis ---
            f.readline()  # section header
            dvr['TStart'] = float_read(f.readline().split()[0])
            ln = f.readline().split()
            dvr['DT'] = ln[0].strip('"')  # may be "DEFAULT"
            ln = f.readline().split()
            dvr['NumTimeSteps'] = ln[0].strip('"')  # may be "DEFAULT" or int

            # Column headers and units
            f.readline()  # column headers
            f.readline()  # column units

            # Timeseries: either @filename or inline data
            line = f.readline().strip()
            if line.startswith('@'):
                dvr['TimeseriesFile'] = line[1:]  # strip @ prefix
                dvr['TimeseriesData'] = []
            else:
                dvr['TimeseriesFile'] = ''
                rows = []
                while line and not line.upper().startswith('END'):
                    parts = line.split()
                    if parts:
                        rows.append([float_read(p) for p in parts])
                    line = f.readline().strip()
                dvr['TimeseriesData'] = rows

        result: Dict[str, Any] = {'AeroDiskDriver': dvr}

        # --- Delegate to AeroDiskIO ---
        adsk_file = dvr.get('ADskIptFile', '')
        adsk_path = os.path.normpath(os.path.join(str(base_dir), adsk_file))
        if adsk_file and os.path.isfile(adsk_path):
            try:
                adsk_data = self._aerodisk.read(Path(adsk_path), base_dir)
                result.update(adsk_data)
            except Exception:
                pass  # module file parse failure — driver data still valid

        return result

    # ------------------------------------------------------------------
    # WRITE
    # ------------------------------------------------------------------
    def write(self, data: dict, dvr_path: Path) -> None:
        """Write an AeroDisk driver file and the referenced AeroDisk input."""
        dvr_path = Path(dvr_path)
        base_dir = dvr_path.parent
        dvr = data['AeroDiskDriver']

        with open(dvr_path, 'w') as f:
            f.write('------- AeroDisk driver v1.0 INPUT FILE ----------------------------------------------------------------------\n')
            f.write(dvr.get('description', 'Generated by OpenFAST_IO') + '\n')
            f.write('--------------------------------------------------------------------------------------------------------------\n')
            f.write('{!s:<35} {:<15} {:}\n'.format(dvr['Echo'], 'Echo', '- Echo input data to <RootName>.ech (flag)'))
            f.write('--------------------------------------------------------------------------------------------------------------\n')

            adsk_name = dvr.get('ADskIptFile', 'adsk_primary.inp')
            f.write('{:<35} {:<15} {:}\n'.format('"' + adsk_name + '"', 'ADskIptFile', '- AeroDisk input file'))
            f.write('{:<35} {:<15} {:}\n'.format('"' + dvr.get('OutRootName', 'adsk_driver') + '"', 'OutRootName', '- RootName for output files'))
            f.write('----- Geometry and Environment -------------------------------------------------------------------------------\n')
            f.write('{:<35} {:<15} {:}\n'.format(dvr['AirDens'], 'AirDens', '- Air density (kg/m^3)'))
            f.write('{:<35} {:<15} {:}\n'.format(dvr['RotorRad'], 'RotorRad', '- Rotor radius (m)'))
            f.write('{:<35} {:<15} {:}\n'.format(dvr['RotorHeight'], 'RotorHeight', '- Rotor height (m)'))
            f.write('{:<35} {:<15} {:}\n'.format(dvr['ShftTilt'], 'ShftTilt', '- Shaft tilt (deg)'))
            f.write('----- Case Analysis ------------------------------------------------------------------------------------------\n')
            f.write('{:<35} {:<15} {:}\n'.format(dvr['TStart'], 'TStart', '- Start time (currently unused)'))
            f.write('{:<35} {:<15} {:}\n'.format('"' + str(dvr['DT']) + '"', 'DT', '- Time step (DEFAULT to use smallest DT from input series)'))
            f.write('{:<35} {:<15} {:}\n'.format(str(dvr['NumTimeSteps']), 'NumTimeSteps', '- Number of timesteps (DEFAULT to run to end of time)'))
            f.write('Time        WndSpeed_X      WndSpeed_Y      WndSpeed_Z      RotSpd         Pitch          Yaw\n')
            f.write('(s)         (m/s)           (m/s)           (m/s)           (rpm)          (deg)          (deg)\n')
            ts_file = dvr.get('TimeseriesFile', '')
            if ts_file:
                f.write('@{}\n'.format(ts_file))
            else:
                for row in dvr.get('TimeseriesData', []):
                    f.write('  '.join(str(v) for v in row) + '\n')

        # --- Delegate to AeroDiskIO ---
        if 'AeroDisk' in data:
            adsk_path = os.path.normpath(os.path.join(str(base_dir), adsk_name))
            try:
                self._aerodisk.write({'AeroDisk': data['AeroDisk']}, adsk_path, str(base_dir))
            except Exception:
                pass
