@test
subroutine test_BD_TrapezoidalPointWeight()
    ! test branches
    ! - calculation made for bd_5MW_dynamic regression test
    ! - 10 random points, refine = 1
    ! - 10 random points, refine = 2
    ! - 10 random points, refine = 3
    ! - 10 random points, refine = 4
    ! - 13 random points, refine = 1
    
    use pFUnit_mod
    use BeamDyn_Subs
    use NWTC_Num
    
    implicit none
    
    integer(IntKi)          :: numpts                     ! Number of quadrature points, will be >= station_total, based on refine
    integer(IntKi)          :: refine                     ! FE mesh refinement factor
    real(BDKi), allocatable :: QPtLocs(:), QPtWeight(:)   ! Quadrature point locations and weights
    integer(IntKi)          :: station_total              ! Number of points in station_eta--qpoints will be >= to this, depending on refine
    real(BDKi), allocatable :: station_eta(:)             ! Station location in eta [0,1]
    
    real(BDKi), allocatable :: BaseLocs(:), BaseWeight(:) ! Baseline quadrature point locations and weights
    
    character(1024)         :: testname
    real(BDKi)              :: tolerance
    
    ! initialize NWTC_Num constants
    call SetConstants()
    
    tolerance = 1e-14
    
    ! --------------------------------------------------------------------------
    testname = "test the inputs/outputs from bd_5MW_dynamic:"

    ! these are the inputs and outputs generated by the bd_5MW_dynamic regression test, as of 5/30/18

    numpts = 49
    station_total = numpts
    refine = 1

    allocate(QPtLocs(numpts), QPtWeight(numpts), station_eta(numpts), BaseLocs(numpts), BaseWeight(numpts))

    station_eta = (/ 0.0000000000000000, 3.2499999999999999E-003, 1.9510000000000000E-002,&
                     3.5770000000000003E-002, 5.2030000000000000E-002, 6.8290000000000003E-002,&
                     8.4550000000000000E-002, 0.10081000000000000, 0.11706999999999999,&
                     0.13335000000000000, 0.14959000000000000, 0.16585000000000000,&
                     0.18210999999999999, 0.19836999999999999, 0.21465000000000001,&
                     0.23089000000000001, 0.24715000000000001, 0.26340999999999998,&
                     0.29594999999999999, 0.32845999999999997, 0.36098000000000002,&
                     0.39350000000000002, 0.42602000000000001, 0.45855000000000001,&
                     0.49106000000000000, 0.52358000000000005, 0.55610000000000004,&
                     0.58862000000000003, 0.62114999999999998, 0.65366000000000002,&
                     0.68618000000000001, 0.71870000000000001, 0.75122000000000000,&
                     0.78376000000000001, 0.81625999999999999, 0.84877999999999998,&
                     0.88129999999999997, 0.89756000000000002, 0.91381999999999997,&
                     0.93008000000000002, 0.93820999999999999, 0.94635999999999998,&
                     0.95447000000000004, 0.96260000000000001, 0.97072999999999998,&
                     0.97885999999999995, 0.98699000000000003, 0.99512000000000000,&
                     1.0000000000000000 /)
    QPtLocs = 0.0_BDKi
    QPtWeight = 0.0_BDKi

    BaseLocs = (/ -1.0000000000000000, -0.99350000000000005, -0.96097999999999995,&
                 -0.92845999999999995, -0.89593999999999996, -0.86341999999999997,&
                 -0.83089999999999997, -0.79837999999999998, -0.76585999999999999,&
                 -0.73330000000000006, -0.70082000000000000, -0.66830000000000001,&
                 -0.63578000000000001, -0.60326000000000002, -0.57069999999999999,&
                 -0.53821999999999992, -0.50570000000000004, -0.47318000000000005,&
                 -0.40810000000000002, -0.34308000000000005, -0.27803999999999995,&
                 -0.21299999999999997, -0.14795999999999998, -8.2899999999999974E-002,&
                 -1.7880000000000007E-002, 4.7160000000000091E-002, 0.11220000000000008,&
                  0.17724000000000006, 0.24229999999999996, 0.30732000000000004,&
                  0.37236000000000002, 0.43740000000000001, 0.50244000000000000,&
                  0.56752000000000002, 0.63251999999999997, 0.69755999999999996,&
                  0.76259999999999994, 0.79512000000000005, 0.82763999999999993,&
                  0.86016000000000004, 0.87641999999999998, 0.89271999999999996,&
                  0.90894000000000008, 0.92520000000000002, 0.94145999999999996,&
                  0.95771999999999990, 0.97398000000000007, 0.99024000000000001,&
                  1.0000000000000000 /)

    BaseWeight = (/ 3.2499999999999751E-003, 1.9510000000000027E-002, 3.2520000000000049E-002,&
                    3.2519999999999993E-002, 3.2519999999999993E-002, 3.2519999999999993E-002,&
                    3.2519999999999993E-002, 3.2519999999999993E-002, 3.2539999999999958E-002,&
                    3.2519999999999993E-002, 3.2500000000000029E-002, 3.2519999999999993E-002,&
                    3.2519999999999993E-002, 3.2540000000000013E-002, 3.2520000000000049E-002,&
                    3.2499999999999973E-002, 3.2519999999999938E-002, 4.8800000000000010E-002,&
                    6.5049999999999997E-002, 6.5030000000000032E-002, 6.5040000000000042E-002,&
                    6.5039999999999987E-002, 6.5049999999999997E-002, 6.5039999999999987E-002,&
                    6.5030000000000032E-002, 6.5040000000000042E-002, 6.5039999999999987E-002,&
                    6.5049999999999941E-002, 6.5039999999999987E-002, 6.5030000000000032E-002,&
                    6.5039999999999987E-002, 6.5039999999999987E-002, 6.5060000000000007E-002,&
                    6.5039999999999987E-002, 6.5019999999999967E-002, 6.5039999999999987E-002,&
                    4.8780000000000046E-002, 3.2519999999999993E-002, 3.2519999999999993E-002,&
                    2.4390000000000023E-002, 1.6279999999999961E-002, 1.6260000000000052E-002,&
                    1.6240000000000032E-002, 1.6259999999999941E-002, 1.6259999999999941E-002,&
                    1.6260000000000052E-002, 1.6260000000000052E-002, 1.3009999999999966E-002,&
                    4.8799999999999955E-003 /)
    
    call BD_TrapezoidalPointWeight(QPtLocs, QPtWeight, numpts, refine, station_eta, station_total)
    
    @assertEqual(BaseLocs, QPtLocs, tolerance, testname)
    @assertEqual(BaseWeight, QPtWeight, tolerance, testname)

    deallocate(QPtLocs, QPtWeight, station_eta, BaseLocs, BaseWeight)
    
    ! --------------------------------------------------------------------------
    testname = "10 randomly chosen points in [0, 1], refine = 1:"
    
    ! the inputs for all of the following tests employ U(0,1) values for station_eta,
    ! and the baseline outputs are generated by a Matlab script (the code is
    ! included at the bottom)
    
    station_total = 10
    refine = 1
    numpts = station_total * refine - (refine - 1)

    allocate(QPtLocs(numpts), QPtWeight(numpts), station_eta(station_total), BaseLocs(numpts), BaseWeight(numpts))

    station_eta = (/ 0.000000000000000, 0.162611735194631, 0.276025076998578,&
                     0.445586200710899, 0.498364051982143, 0.646313010111265,&
                     0.655098003973841, 0.679702676853675, 0.709364830858073,&
                     1.000000000000000 /)
    QPtLocs = 0.0_BDKi
    QPtWeight = 0.0_BDKi

    BaseLocs = (/ -1.000000000000000, -0.674776529610739, -0.447949846002843,&
                  -0.108827598578201, -0.003271896035714, 0.292626020222529,&
                   0.310196007947681, 0.359405353707350, 0.418729661716145,&
                   1.000000000000000 /)

    BaseWeight = (/ 0.162611735194631, 0.276025076998578, 0.282974465516269,&
                    0.222338974983565, 0.200726809400365, 0.156733951991698,&
                    0.033389666742410, 0.054266826884232, 0.320297323146325,&
                    0.290635169141927 /)

    call BD_TrapezoidalPointWeight(QPtLocs, QPtWeight, numpts, refine, station_eta, station_total)
    
    @assertEqual(BaseLocs, QPtLocs, tolerance, testname)
    @assertEqual(BaseWeight, QPtWeight, tolerance, testname)

    deallocate(QPtLocs, QPtWeight, station_eta, BaseLocs, BaseWeight)
    
    ! --------------------------------------------------------------------------
    testname = "10 randomly chosen points in [0, 1], refine = 2:"
    
    station_total = 10
    refine = 2
    numpts = station_total * refine - (refine - 1)

    allocate(QPtLocs(numpts), QPtWeight(numpts), station_eta(station_total), BaseLocs(numpts), BaseWeight(numpts))

    station_eta = (/ 0.000000000000000, 0.251083857976031, 0.349983765984809,&
                     0.351659507062997, 0.473288848902729, 0.549723608291140,&
                     0.585264091152724, 0.616044676146639, 0.830828627896291,&
                     1.000000000000000 /)
    QPtLocs = 0.0_BDKi
    QPtWeight = 0.0_BDKi

    BaseLocs = (/ -1.000000000000000, -0.748916142023969, -0.497832284047938,&
                  -0.398932376039160, -0.300032468030383, -0.298356726952195,&
                  -0.296680985874006, -0.175051644034274, -0.053422302194541,&
                   0.023012457193869, 0.099447216582279, 0.134987699443864,&
                   0.170528182305449, 0.201308767299363, 0.232089352293278,&
                   0.446873304042930, 0.661657255792582, 0.830828627896291,&
                   1.000000000000000 /)

    BaseWeight = (/ 0.125541928988016, 0.251083857976031, 0.174991882992404,&
                    0.098899908008778, 0.050287824543483, 0.001675741078188,&
                    0.061652541458960, 0.121629341839733, 0.099032050614071,&
                    0.076434759388410, 0.055987621124998, 0.035540482861585,&
                    0.033160533927750, 0.030780584993915, 0.122782268371783,&
                    0.214783951749652, 0.191977661926680, 0.169171372103709,&
                    0.084585686051855 /)

    call BD_TrapezoidalPointWeight(QPtLocs, QPtWeight, numpts, refine, station_eta, station_total)
    
    @assertEqual(BaseLocs, QPtLocs, tolerance, testname)
    @assertEqual(BaseWeight, QPtWeight, tolerance, testname)

    deallocate(QPtLocs, QPtWeight, station_eta, BaseLocs, BaseWeight)

    ! --------------------------------------------------------------------------
    testname = "10 randomly chosen points in [0, 1], refine = 3:"
    
    station_total = 10
    refine = 3
    numpts = station_total * refine - (refine - 1)

    allocate(QPtLocs(numpts), QPtWeight(numpts), station_eta(station_total), BaseLocs(numpts), BaseWeight(numpts))

    station_eta = (/ 0.000000000000000, 0.152378018969223, 0.228976968716819,&
                     0.262971284540144, 0.450541598502498, 0.654079098476782,&
                     0.689214503140008, 0.748151592823709, 0.825816977489547,&
                     1.000000000000000 /)
    QPtLocs = 0.0_BDKi
    QPtWeight = 0.0_BDKi

    BaseLocs = (/ -1.000000000000000, -0.898414654020518, -0.796829308041036,&
                  -0.695243962061554, -0.644177995563157, -0.593112029064760,&
                  -0.542046062566362, -0.519383185350812, -0.496720308135262,&
                  -0.474057430919711, -0.349010554944809, -0.223963678969907,&
                  -0.098916802995004, 0.036774863654518, 0.172466530304042,&
                   0.308158196953565, 0.331581800062382, 0.355005403171198,&
                   0.378429006280016, 0.417720399402483, 0.457011792524951,&
                   0.496303185647419, 0.548080108757978, 0.599857031868536,&
                   0.651633954979095, 0.767755969986063, 0.883877984993032,&
                   1.000000000000000 /)

    BaseWeight = (/ 0.050792672989741, 0.101585345979482, 0.101585345979482,&
                    0.076325656238940, 0.051065966498397, 0.051065966498397,&
                    0.036864421856974, 0.022662877215550, 0.022662877215550,&
                    0.073854876595226, 0.125046875974902, 0.125046875974902,&
                    0.130369271312213, 0.135691666649523, 0.135691666649523,&
                    0.079557634879170, 0.023423603108817, 0.023423603108817,&
                    0.031357498115642, 0.039291393122468, 0.039291393122468,&
                    0.045534158116513, 0.051776923110559, 0.051776923110559,&
                    0.083949469058764, 0.116122015006968, 0.116122015006968,&
                    0.058061007503484 /)

    call BD_TrapezoidalPointWeight(QPtLocs, QPtWeight, numpts, refine, station_eta, station_total)
    
    @assertEqual(BaseLocs, QPtLocs, tolerance, testname)
    @assertEqual(BaseWeight, QPtWeight, tolerance, testname)

    deallocate(QPtLocs, QPtWeight, station_eta, BaseLocs, BaseWeight)

    ! --------------------------------------------------------------------------
    testname = "10 randomly chosen points in [0, 1], refine = 4:"
    
    station_total = 10
    refine = 4
    numpts = station_total * refine - (refine - 1)

    allocate(QPtLocs(numpts), QPtWeight(numpts), station_eta(station_total), BaseLocs(numpts), BaseWeight(numpts))

    station_eta = (/ 0.000000000000000, 0.046171390631154, 0.097131781235848,&
                     0.171186687811562, 0.276922984960890, 0.392227019534168,&
                     0.655477890177557, 0.706046088019609, 0.743132468124916,&
                     1.000000000000000 /)
    QPtLocs = 0.0_BDKi
    QPtWeight = 0.0_BDKi

    BaseLocs = (/ -1.000000000000000, -0.976914304684423, -0.953828609368846,&
                  -0.930742914053269, -0.907657218737692, -0.882177023435345,&
                  -0.856696828132998, -0.831216632830651, -0.805736437528304,&
                  -0.768708984240447, -0.731681530952590, -0.694654077664733,&
                  -0.657626624376876, -0.604758475802212, -0.551890327227548,&
                  -0.499022178652884, -0.446154030078220, -0.388502012791581,&
                  -0.330849995504942, -0.273197978218303, -0.215545960931664,&
                  -0.083920525609970, 0.047704909711725, 0.179330345033419,&
                   0.310955780355114, 0.336239879276140, 0.361523978197166,&
                   0.386808077118192, 0.412092176039218, 0.430635366091872,&
                   0.449178556144525, 0.467721746197178, 0.486264936249832,&
                   0.614698702187374, 0.743132468124916, 0.871566234062458,&
                   1.000000000000000 /)

    BaseWeight = (/ 0.011542847657789, 0.023085695315577, 0.023085695315577,&
                    0.023085695315577, 0.024282945308962, 0.025480195302347,&
                    0.025480195302347, 0.025480195302347, 0.031253824295102,&
                    0.037027453287857, 0.037027453287857, 0.037027453287857,&
                    0.044947800931260, 0.052868148574664, 0.052868148574664,&
                    0.052868148574664, 0.055260082930651, 0.057652017286639,&
                    0.057652017286639, 0.057652017286639, 0.094638726304167,&
                    0.131625435321695, 0.131625435321694, 0.131625435321694,&
                    0.078454767121360, 0.025284098921026, 0.025284098921026,&
                    0.025284098921026, 0.021913644486840, 0.018543190052653,&
                    0.018543190052653, 0.018543190052653, 0.073488477995098,&
                    0.128433765937542, 0.128433765937542, 0.128433765937542,&
                    0.064216882968771 /)

    call BD_TrapezoidalPointWeight(QPtLocs, QPtWeight, numpts, refine, station_eta, station_total)
    
    @assertEqual(BaseLocs, QPtLocs, tolerance, testname)
    @assertEqual(BaseWeight, QPtWeight, tolerance, testname)

    deallocate(QPtLocs, QPtWeight, station_eta, BaseLocs, BaseWeight)

    ! --------------------------------------------------------------------------
    testname = "13 randomly chosen points in [0, 1], refine = 1:"
    
    station_total = 13
    refine = 1
    numpts = station_total * refine - (refine - 1)

    allocate(QPtLocs(numpts), QPtWeight(numpts), station_eta(station_total), BaseLocs(numpts), BaseWeight(numpts))

    station_eta = (/ 0.000000000000000, 0.144954798223727, 0.145538980384717,&
                     0.181847028302852, 0.263802916521990, 0.431413827463545,&
                     0.549860201836332, 0.579704587365570, 0.622055131485066,&
                     0.800068480224308, 0.853031117721894, 0.869292207640089,&
                     1.000000000000000 /)
    QPtLocs = 0.0_BDKi
    QPtWeight = 0.0_BDKi

    BaseLocs = (/ -1.000000000000000, -0.710090403552546, -0.708922039230566,&
                  -0.636305943394295, -0.472394166956020, -0.137172345072911,&
                   0.099720403672664, 0.159409174731140, 0.244110262970132,&
                   0.600136960448615, 0.706062235443787, 0.738584415280179,&
                   1.000000000000000 /)

    BaseWeight = (/ 0.144954798223727, 0.145538980384717, 0.036892230079126,&
                   0.118263936137273, 0.249566799160692, 0.286057285314342,&
                   0.148290759902026, 0.072194929648734, 0.220363892858737,&
                   0.230975986236828, 0.069223727415782, 0.146968882278106,&
                   0.130707792359911 /)

    call BD_TrapezoidalPointWeight(QPtLocs, QPtWeight, numpts, refine, station_eta, station_total)
    
    @assertEqual(BaseLocs, QPtLocs, tolerance, testname)
    @assertEqual(BaseWeight, QPtWeight, tolerance, testname)

    deallocate(QPtLocs, QPtWeight, station_eta, BaseLocs, BaseWeight)
    
end subroutine test_BD_TrapezoidalPointWeight

! ! this is the Matlab script used to generate the outputs for the tests above
! ! it is based on BD_TrapezoidalPointWeight(), itself, as it is on 5/30/18
! format long

! station_total = 10;
! id0 = 1;
! refine = 1;
! numpts = station_total * refine - (refine - 1);
! QPtLocs = zeros(1, numpts);
! QPtWeight = zeros(1, numpts);

! % use this to generate a new random eta vector
! % station_eta = sort(rand(1, station_total, 'double'));
! % station_eta(1) = 0;
! % station_eta(end) = 1;
! % station_eta

! % % fill this in to use a specific eta vector
! station_eta = [0.000000000000000, 0.162611735194631, 0.276025076998578,...
!                0.445586200710899, 0.498364051982143, 0.646313010111265,...
!                0.655098003973841, 0.679702676853675, 0.709364830858073,...
!                1.000000000000000]

! QPtLocs(1) = station_eta(1);
! for j = 2 : numpts
!     indx =  1 + fix((j - 2) / refine);
!     QPtLocs(j) =  station_eta(indx) + ((station_eta(indx + 1) - station_eta(indx)) / refine) * (mod(j - 2, refine) + 1);
! end    
! QPtLocs = 2.0 * QPtLocs - 1.0

! id1 = station_total;
! temp_id0 = (id0 - 1) * refine + 1;
! temp_id1 = (id1 - 1) * refine + 1;
! denom = QPtLocs(temp_id1) - QPtLocs(temp_id0);

! QPtWeight(1)     =  (QPtLocs(temp_id0 + 1) - QPtLocs(temp_id0)) / denom;
! for j = 2 : numpts - 1
!     QPtWeight(j)  =  (QPtLocs(temp_id0 + j) - QPtLocs(temp_id0 + j - 2)) / denom;
! end
! QPtWeight(numpts) =  (QPtLocs(temp_id1) - QPtLocs(temp_id1 - 1)) / denom

