name: 'Configure CMake'
description: 'Configure the CMake project'
author: 'Rafael Mudafort https://github.com/rafmudaf'

inputs:
  build-type:
    description: 'Set the CMake build type: Release (-O3); RelWithDebInfo (-O2 -g); Debug (-g)'
    default: 'Release'
  additional-flags:
    description: 'Additional flags to pass directly to the CMake command'
    default: ''

runs:
  using: 'composite'
  steps:
    - run: cmake .. -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} ${{ inputs.additional-flags }} 
      working-directory: "/openfast/build"
      shell: bash
