char *template_c2f_helpers[] = {
"",
"#ifdef NOUNDERSCORE",
"# define ModName_COPY_FLOAT_1DC_1DF ModName_copy_float_1dc_1df",
"# define ModName_COPY_FLOAT_1DC_2DF ModName_copy_float_1dc_2df",
"# define ModName_COPY_FLOAT_1DC_3DF ModName_copy_float_1dc_3df",
"# define ModName_COPY_DOUBLE_1DC_1DF ModName_copy_double_1dc_1df",
"# define ModName_COPY_DOUBLE_1DC_2DF ModName_copy_double_1dc_2df",
"# define ModName_COPY_DOUBLE_1DC_3DF ModName_copy_double_1dc_3df",
"# define ModName_COPY_INT_1DC_1DF ModName_copy_int_1dc_1df",
"# define ModName_COPY_INT_1DC_2DF ModName_copy_int_1dc_2df",
"# define ModName_COPY_INT_1DC_3DF ModName_copy_int_1dc_3df",
"#else",
"# ifdef F2C_STYLE",
"#  define ModName_COPY_FLOAT_1DC_1DF ModName_copy_float_1dc_1df__",
"#  define ModName_COPY_FLOAT_1DC_2DF ModName_copy_float_1dc_2df__",
"#  define ModName_COPY_FLOAT_1DC_3DF ModName_copy_float_1dc_3df__",
"#  define ModName_COPY_DOUBLE_1DC_1DF ModName_copy_double_1dc_1df__",
"#  define ModName_COPY_DOUBLE_1DC_2DF ModName_copy_double_1dc_2df__",
"#  define ModName_COPY_DOUBLE_1DC_3DF ModName_copy_double_1dc_3df__",
"#  define ModName_COPY_INT_1DC_1DF ModName_copy_int_1dc_1df__",
"#  define ModName_COPY_INT_1DC_2DF ModName_copy_int_1dc_2df__",
"#  define ModName_COPY_INT_1DC_3DF ModName_copy_int_1dc_3df__",
"# else",
"#  define ModName_COPY_FLOAT_1DC_1DF ModName_copy_float_1dc_1df_",
"#  define ModName_COPY_FLOAT_1DC_2DF ModName_copy_float_1dc_2df_",
"#  define ModName_COPY_FLOAT_1DC_3DF ModName_copy_float_1dc_3df_",
"#  define ModName_COPY_DOUBLE_1DC_1DF ModName_copy_double_1dc_1df_",
"#  define ModName_COPY_DOUBLE_1DC_2DF ModName_copy_double_1dc_2df_",
"#  define ModName_COPY_DOUBLE_1DC_3DF ModName_copy_double_1dc_3df_",
"#  define ModName_COPY_INT_1DC_1DF ModName_copy_int_1dc_1df_",
"#  define ModName_COPY_INT_1DC_2DF ModName_copy_int_1dc_2df_",
"#  define ModName_COPY_INT_1DC_3DF ModName_copy_int_1dc_3df_",
"# endif",
"#endif",
"",
"void ModName_COPY_FLOAT_1DC_1DF (float * src, float * dst , int *i1 ) {",
"  int i ;",
"  float *p ;",
"  p = src ;",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i ] = *p++ ; } }",
"",
"void ModName_COPY_FLOAT_1DC_2DF (float * src, float * dst , int *i1, int *i2 ) {",
"  int i,j ;",
"  float *p ;",
"  p = src ;",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i + j*(*i1)  ] = *p++ ; } }",
"",
"void ModName_COPY_FLOAT_1DC_3DF (float * src, float * dst , int *i1, int *i2, int *i3 ) {",
"  int i,j,k ;",
"  float *p ;",
"  p = src ;",
"  for ( k = 0 ; k < *i3 ; k++ )",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i + j*(*i1) + k*( *i1 * *i2 ) ] = *p++ ; } }",
"",
"",
"void ModName_COPY_DOUBLE_1DC_1DF (double * src, double * dst , int *i1 ) {",
"  int i ;",
"  double *p ;",
"  p = src ;",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i ] = *p++ ; } }",
"",
"void ModName_COPY_DOUBLE_1DC_2DF (double * src, double * dst , int *i1, int *i2 ) {",
"  int i,j ;",
"  double *p ;",
"  p = src ;",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i + j*(*i1)  ] = *p++ ; } }",
"",
"void ModName_COPY_DOUBLE_1DC_3DF (double * src, double * dst , int *i1, int *i2, int *i3 ) {",
"  int i,j,k ;",
"  double *p ;",
"  p = src ;",
"  for ( k = 0 ; k < *i3 ; k++ )",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i + j*(*i1) + k*( *i1 * *i2 ) ] = *p++ ; } }",
"",
"",
"void ModName_COPY_INT_1DC_1DF (int * src, int * dst , int *i1 ) {",
"  int i ;",
"  int *p ;",
"  p = src ;",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i ] = *p++ ; } }",
"",
"void ModName_COPY_INT_1DC_2DF (int * src, int * dst , int *i1, int *i2 ) {",
"  int i,j ;",
"  int *p ;",
"  p = src ;",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i + j*(*i1)  ] = *p++ ; } }",
"",
"void ModName_COPY_INT_1DC_3DF (int * src, int * dst , int *i1, int *i2, int *i3 ) {",
"  int i,j,k ;",
"  int *p ;",
"  p = src ;",
"  for ( k = 0 ; k < *i3 ; k++ )",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { dst[ i + j*(*i1) + k*( *i1 * *i2 ) ] = *p++ ; } }",
"",
"#ifdef NOUNDERSCORE",
"# define ModName_COPY_FLOAT_1DF_1DC ModName_copy_float_1df_1dc",
"# define ModName_COPY_FLOAT_2DF_1DC ModName_copy_float_2df_1dc",
"# define ModName_COPY_FLOAT_3DF_1DC ModName_copy_float_3df_1dc",
"# define ModName_COPY_DOUBLE_1DF_1DC ModName_copy_double_1df_1dc",
"# define ModName_COPY_DOUBLE_2DF_1DC ModName_copy_double_2df_1dc",
"# define ModName_COPY_DOUBLE_3DF_1DC ModName_copy_double_3df_1dc",
"# define ModName_COPY_INT_1DF_1DC ModName_copy_int_1df_1dc",
"# define ModName_COPY_INT_2DF_1DC ModName_copy_int_2df_1dc",
"# define ModName_COPY_INT_3DF_1DC ModName_copy_int_3df_1dc",
"#else",
"# ifdef F2C_STYLE",
"#  define ModName_COPY_FLOAT_1DF_1DC ModName_copy_float_1df_1dc__",
"#  define ModName_COPY_FLOAT_2DF_1DC ModName_copy_float_2df_1dc__",
"#  define ModName_COPY_FLOAT_3DF_1DC ModName_copy_float_3df_1dc__",
"#  define ModName_COPY_DOUBLE_1DF_1DC ModName_copy_double_1df_1dc__",
"#  define ModName_COPY_DOUBLE_2DF_1DC ModName_copy_double_2df_1dc__",
"#  define ModName_COPY_DOUBLE_3DF_1DC ModName_copy_double_3df_1dc__",
"#  define ModName_COPY_INT_1DF_1DC ModName_copy_int_1df_1dc__",
"#  define ModName_COPY_INT_2DF_1DC ModName_copy_int_2df_1dc__",
"#  define ModName_COPY_INT_3DF_1DC ModName_copy_int_3df_1dc__",
"# else",
"#  define ModName_COPY_FLOAT_1DF_1DC ModName_copy_float_1df_1dc_",
"#  define ModName_COPY_FLOAT_2DF_1DC ModName_copy_float_2df_1dc_",
"#  define ModName_COPY_FLOAT_3DF_1DC ModName_copy_float_3df_1dc_",
"#  define ModName_COPY_DOUBLE_1DF_1DC ModName_copy_double_1df_1dc_",
"#  define ModName_COPY_DOUBLE_2DF_1DC ModName_copy_double_2df_1dc_",
"#  define ModName_COPY_DOUBLE_3DF_1DC ModName_copy_double_3df_1dc_",
"#  define ModName_COPY_INT_1DF_1DC ModName_copy_int_1df_1dc_",
"#  define ModName_COPY_INT_2DF_1DC ModName_copy_int_2df_1dc_",
"#  define ModName_COPY_INT_3DF_1DC ModName_copy_int_3df_1dc_",
"# endif",
"#endif",
"",
"void ModName_COPY_FLOAT_1DF_1DC(float * src, float * dst , int *i1 ) {",
"  int i ;",
"  float *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(float*)malloc(*i1*sizeof(float)) ;",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i ] ; } }",
"void ModName_COPY_FLOAT_2DF_1DC(float * src, float * dst , int *i1, int *i2 ) {",
"  int i,j ;",
"  float *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(float*)malloc(*i2 * *i1*sizeof(float)) ;",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i + j*(*i1)  ] ; } }",
"void ModName_COPY_FLOAT_3DF_1DC(float * src, float * dst , int *i1, int *i2, int *i3 ) {",
"  int i,j,k ;",
"  float *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(float*)malloc(*i3 * *i2 * *i1*sizeof(float)) ;",
"  for ( k = 0 ; k < *i3 ; k++ )",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i + j*(*i1) + k*( *i1 * *i2 ) ] ; } }",
"",
"void ModName_COPY_DOUBLE_1DF_1DC(double * src, double * dst , int *i1 ) {",
"  int i ;",
"  double *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(double*)malloc(*i1*sizeof(double)) ;",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i ] ; } }",
"void ModName_COPY_DOUBLE_2DF_1DC(double * src, double * dst , int *i1, int *i2 ) {",
"  int i,j ;",
"  double *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(double*)malloc(*i2 * *i1*sizeof(double)) ;",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i + j*(*i1)  ] ; } }",
"void ModName_COPY_DOUBLE_3DF_1DC(double * src, double * dst , int *i1, int *i2, int *i3 ) {",
"  int i,j,k ;",
"  double *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(double*)malloc(*i3 * *i2 * *i1*sizeof(double)) ;",
"  for ( k = 0 ; k < *i3 ; k++ )",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i + j*(*i1) + k*( *i1 * *i2 ) ] ; } }",
"",
"void ModName_COPY_INT_1DF_1DC(int * src, int * dst , int *i1 ) {",
"  int i ;",
"  int *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(int*)malloc(*i1*sizeof(int)) ;",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i ] ; } }",
"void ModName_COPY_INT_2DF_1DC(int * src, int * dst , int *i1, int *i2 ) {",
"  int i,j ;",
"  int *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(int*)malloc(*i2 * *i1*sizeof(int)) ;",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i + j*(*i1)  ] ; } }",
"void ModName_COPY_INT_3DF_1DC(int * src, int * dst , int *i1, int *i2, int *i3 ) {",
"  int i,j,k ;",
"  int *p ;",
"  p = src ;",
"  if ( dst != NULL ) free(dst) ;",
"  dst=(int*)malloc(*i3 * *i2 * *i1*sizeof(int)) ;",
"  for ( k = 0 ; k < *i3 ; k++ )",
"  for ( j = 0 ; j < *i2 ; j++ )",
"  for ( i = 0 ; i < *i1 ; i++ )",
"  { *p++ = dst[ i + j*(*i1) + k*( *i1 * *i2 ) ] ; } }",
"",
0L } ;
