name: 'NWTC Library module tests'
description: 'Run tests specific to the NWTC Library module'
author: 'Rafael Mudafort https://github.com/rafmudaf'
runs:
  using: "composite"
  steps: 
    - run: ctest -VV -R nwtc_library_utest
      working-directory: ${{runner.workspace}}/build
      shell: bash
