name: 'Update the existin OpenFAST project in the Docker image'
description: 'Workaround to avoid recompiling every component since the Docker image has the latest "dev" branch precompiled.'
author: 'Rafael Mudafort https://github.com/rafmudaf'

inputs:
  repository:
    description: 'The GitHub repository that is taking action.'
    required: true
  ref:
    description: 'The branch or tag ref that triggered the action.'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        git config --global user.email "openfast@github_actions.ci"
        git config --global user.name "OpenFAST Continuous Integration"
        git pull --no-verify https://github.com/${{ inputs.repository }} ${{ inputs.ref }}
        git submodule update
      working-directory: "/openfast/"
      shell: bash
